resource_group_name = "rsg-raptor-main"
location            = "East US"
cluster_name        = "aks-raptor"
kubernetes_version  = "1.28.9"
system_node_count   = 2
system_node_size    = "Standard_DS2_v2"
node_resource_group = "rsg-raptor-workers"
tag_billing_team    = "raptor"
tag_env             = "development"